name: Auto-Ready Draft PRs

on:
  pull_request:
    types: [opened]

jobs:
  convert-to-ready:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as ready for review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              draft: false
            })
